[gin]
port = ":8080"
# Mysql
mysql.dsn = "alarm:123.com@tcp(127.0.0.1:3306)/alarm?charset=utf8"
# Redis
redis.addr = "127.0.0.1:6379"
redis.password = ""
redis.db = 0

token.privateKeyPath = "."
# token.accessValidity = 3600   # 1小时
token.accessValidity = 172800  # 1小时
token.refreshValidity = 172800 # 2天

account.superAdminID = 1
account.defaultPassword = "dc483e80a7a0bd9ef71d8cf973673924"

[listener]
rabbitmqurl = "amqp://user:mkjsix7@1.12.250.106:5672/"
[[listener.mails]]
name = "yangquanmailtest@163.com"
password = "APQJNHKHMXPGRFVO"
host = "smtp.163.com"
port = 25
